// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQmNQxlmsm4pMhQgidqFw-zQ2b6xicU_A',
    appId: '1:20138767712:web:035289004dbc7f40c99a05',
    messagingSenderId: '20138767712',
    projectId: 'dstnotes',
    authDomain: 'dstnotes.firebaseapp.com',
    storageBucket: 'dstnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4Rrc0uNXxAHjCLeBWmcFCMzz-nzLz5Y',
    appId: '1:20138767712:android:0cbd7279d2a654bac99a05',
    messagingSenderId: '20138767712',
    projectId: 'dstnotes',
    storageBucket: 'dstnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzc6LC31jvmqcuVo_BK0woxj4eEregps',
    appId: '1:20138767712:ios:e1fd46b2e065d3e7c99a05',
    messagingSenderId: '20138767712',
    projectId: 'dstnotes',
    storageBucket: 'dstnotes.appspot.com',
    iosClientId: '20138767712-8d8q5aor2u9j3al81dt3d9lc0v8r62im.apps.googleusercontent.com',
    iosBundleId: 'com.dest.dstnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzc6LC31jvmqcuVo_BK0woxj4eEregps',
    appId: '1:20138767712:ios:e1fd46b2e065d3e7c99a05',
    messagingSenderId: '20138767712',
    projectId: 'dstnotes',
    storageBucket: 'dstnotes.appspot.com',
    iosClientId: '20138767712-8d8q5aor2u9j3al81dt3d9lc0v8r62im.apps.googleusercontent.com',
    iosBundleId: 'com.dest.dstnotes',
  );
}
